CREATE DATABASE funs;

DROP TABLE IF EXISTS `ADMIN`;
CREATE TABLE `ADMIN` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `PASSWORD` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `STATE` tinyint(1) NOT NULL DEFAULT '1',
  `SALT` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `user_name_unique` (`USER_NAME`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE `ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `role_name_unique` (`ROLE_NAME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


DROP TABLE IF EXISTS `ADMIN_ROLE`;
CREATE TABLE `ADMIN_ROLE` (
  `ADMIN_ID` int(11),
  `ROLE_ID` int(11),
  PRIMARY KEY (`ADMIN_ID`,`ROLE_ID`),
  KEY `admin_role_foreign` (`ROLE_ID`) USING BTREE,
  CONSTRAINT `fk_ref_admin` FOREIGN KEY (`ADMIN_ID`) REFERENCES `ADMIN` (`ID`),
  CONSTRAINT `fk_ref_role` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


DROP TABLE IF EXISTS `PERMISSION`;
CREATE TABLE `PERMISSION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PERMISSION_NAME` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `PERMISSION_CODE` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `PARENT_ID` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `PARENT_IDS` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `UPDATE_DATE` datetime NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `permission_code_unique` (`PERMISSION_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


DROP TABLE IF EXISTS `ROLE_PERMISSION`;
CREATE TABLE `ROLE_PERMISSION` (
  `ROLE_ID` int(11),
  `PERMISSION_ID` int(11),
  PRIMARY KEY (`ROLE_ID`,`PERMISSION_ID`),
  KEY `role_permission_foreign` (`PERMISSION_ID`) USING BTREE,
  CONSTRAINT `fk_ref_permission` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `PERMISSION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
